### ISSUE TITLE
Kernel version 5.13.0-valve37-1-neptune is NOT supported by this script!

### ISSUE THREAD

**Issue by rpalmerdev** [ryanrudolfoba/SteamDeck-vangogh_oc_fix-installer#1]
Getting that error when copying the script into the terminal on Steam Deck. 

Running Steam OS on the stable branch. BIOS vers. F7A0116.

**Comment by ryanrudolfoba** [comment]
sorry for late reply.

there was a minor typo in the script for the kernel version check, i used a dot instead of a dash.

![image](https://github.com/ryanrudolfoba/SteamDeck-vangogh_oc_fix-installer/assets/98122529/6e7038f1-7371-460a-8106-92dc1e3c7c6b)

i updated it now.
