### ISSUE TITLE
Kernel version 6.1.52-valve9-1-neptune-61 is not supported by this script

### ISSUE THREAD

**Issue by chigo96** [ryanrudolfoba/SteamDeck-vangogh_oc_fix-installer#2]
I'm running steamos on the stable build with bios 116 and I get this error

![Screenshot_20231129_221001](https://github.com/ryanrudolfoba/SteamDeck-vangogh_oc_fix-installer/assets/122126841/81364da8-89b3-4955-87b9-e32ab1696a19)

**Comment by ryanrudolfoba** [comment]
i've complied the vangogh_oc_fix against 3.5.7 and updated the script.
please clone the repo to get the latest version.

![image](https://github.com/ryanrudolfoba/SteamDeck-vangogh_oc_fix-installer/assets/98122529/22507d0c-5189-49a7-a71a-4943624588df)

**Comment by chigo96** [comment]
thank you so much
