### ISSUE TITLE
Do not install this kernel module before Samsung's overclocking RAM

### ISSUE THREAD

**Issue by lzq960605** [ryanrudolfoba/SteamDeck-vangogh_oc_fix-installer#5]
As the title suggests,Even with the battery removed and the combination keys unable to reset the BIOS settings, I have logged in to RAM 3200. I have already ordered the ch341a package, which will arrive in 2-3 days. I have noticed that others have restored the backup BIOS through ch341a, and I hope I can successfully save it

**Comment by lzq960605** [comment]
This kernel module seems to patch the BIOS and then re flush, which makes it impossible for me to reset the BIOS to the default settings no matter what

**Comment by ryanrudolfoba** [comment]
It doesnt touch / modify the BIOS. And you have to manually activate the kernel module.

**Comment by lzq960605** [comment]
> 它不会触及/修改 BIOS。并且您必须手动激活内核模块。

After I installed it, he flashed the BIOS again. Before installing this module, I was able to reset the BIOS settings by overclocking the RAM. However, after installing this module, I was still unable to reset the BIOS settings by overclocking the RAM
