### ISSUE TITLE
Stable 3.6 update

### ISSUE THREAD

**Issue by thefakesound** [ryanrudolfoba/SteamDeck-vangogh_oc_fix-installer#8]
Hello.
Could you please update fix installer for new stable release 3.6.19 and maybe for 3.7 beta?

**Comment by Rhylthus** [comment]
Would also appreciate if you could update your tool!  thanks

**Comment by ryanrudolfoba** [comment]
script has been updated to support 3.6.19 stable

![image](https://github.com/user-attachments/assets/0684eca1-6caa-44d2-acbb-8a852efcda67)
